- name: Set arm64 architecture
  set_fact:
    inbucket_arch: arm64
  when: ansible_facts['ansible_architecture'] == "aarch64"

- name: Set arm64 architecture
  set_fact:
    inbucket_arch: amd64
  when: ansible_facts['ansible_architecture'] != "aarch64"

- name: Install Inbucket
  ansible.builtin.apt:
    deb: "https://github.com/inbucket/inbucket/releases/download/v{{ inbucket_version }}/inbucket_{{ inbucket_version }}_linux_{{ inbucket_arch }}.deb"
  notify: restart inbucket